wandb_version: 1

weights:
  desc: null
  value: yolov7.pt
cfg:
  desc: null
  value: cfg/training/yolov7.yaml
data:
  desc: null
  value: data/custom.yaml
hyp:
  desc: null
  value:
    lr0: 0.01
    lrf: 0.1
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 0.05
    cls: 0.3
    cls_pw: 1.0
    obj: 0.7
    obj_pw: 1.0
    iou_t: 0.2
    anchor_t: 4.0
    fl_gamma: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.2
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0
    copy_paste: 0.0
    paste_in: 0.0
    loss_ota: 1
epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 8
img_size:
  desc: null
  value:
  - 640
  - 640
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
noautoanchor:
  desc: null
  value: false
evolve:
  desc: null
  value: false
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
image_weights:
  desc: null
  value: false
device:
  desc: null
  value: '0'
multi_scale:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
adam:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
workers:
  desc: null
  value: 4
project:
  desc: null
  value: runs/train
entity:
  desc: null
  value: null
name:
  desc: null
  value: yolov7-custom
exist_ok:
  desc: null
  value: false
quad:
  desc: null
  value: false
linear_lr:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
upload_dataset:
  desc: null
  value: false
bbox_interval:
  desc: null
  value: -1
save_period:
  desc: null
  value: -1
artifact_alias:
  desc: null
  value: latest
freeze:
  desc: null
  value:
  - 0
v5_metric:
  desc: null
  value: false
verbose:
  desc: null
  value: transformation
world_size:
  desc: null
  value: 1
global_rank:
  desc: null
  value: -1
save_dir:
  desc: null
  value: runs/train/yolov7-custom39
total_batch_size:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699998098.722462
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 19
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
opt:
  desc: null
  value:
    weights: yolov7.pt
    cfg: cfg/training/yolov7.yaml
    data: data/custom.yaml
    hyp:
      lr0: 0.01
      lrf: 0.1
      momentum: 0.937
      weight_decay: 0.0005
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      warmup_bias_lr: 0.1
      box: 0.05
      cls: 0.3
      cls_pw: 1.0
      obj: 0.7
      obj_pw: 1.0
      iou_t: 0.2
      anchor_t: 4.0
      fl_gamma: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      degrees: 0.0
      translate: 0.2
      scale: 0.5
      shear: 0.0
      perspective: 0.0
      flipud: 0.0
      fliplr: 0.5
      mosaic: 1.0
      mixup: 0.0
      copy_paste: 0.0
      paste_in: 0.0
      loss_ota: 1
    epochs: 20
    batch_size: 8
    img_size:
    - 640
    - 640
    rect: false
    resume: false
    nosave: false
    notest: false
    noautoanchor: false
    evolve: false
    bucket: ''
    cache_images: false
    image_weights: false
    device: '0'
    multi_scale: false
    single_cls: false
    adam: false
    sync_bn: false
    local_rank: -1
    workers: 4
    project: runs/train
    entity: null
    name: yolov7-custom
    exist_ok: false
    quad: false
    linear_lr: false
    label_smoothing: 0.0
    upload_dataset: false
    bbox_interval: -1
    save_period: -1
    artifact_alias: latest
    freeze:
    - 0
    v5_metric: false
    verbose: transformation
    world_size: 1
    global_rank: -1
    save_dir: runs/train/yolov7-custom39
    total_batch_size: 8
data_dict:
  desc: null
  value:
    train: ./coco/train2017.txt
    val: ./coco/val2017.txt
    test: ./coco/test-dev2017.txt
    nc: 80
    names:
    - person
    - bicycle
    - car
    - motorcycle
    - airplane
    - bus
    - train
    - truck
    - boat
    - traffic light
    - fire hydrant
    - stop sign
    - parking meter
    - bench
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - backpack
    - umbrella
    - handbag
    - tie
    - suitcase
    - frisbee
    - skis
    - snowboard
    - sports ball
    - kite
    - baseball bat
    - baseball glove
    - skateboard
    - surfboard
    - tennis racket
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
    - chair
    - couch
    - potted plant
    - bed
    - dining table
    - toilet
    - tv
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush
